repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: poetry run flake8
        pass_filenames: true
        types: [ python ]
        files: \.py$

      - id: isort
        name: isort
        language: system
        entry: poetry run isort --check
        pass_filenames: true
        types: [ python ]
        files: \.py$

      - id: mypy
        name: mypy
        language: system
        entry: poetry run mypy
        pass_filenames: true
        types: [ python ]
        files: \.py$

      - id: test
        name: test
        language: system
        entry: poetry run pytest
        pass_filenames: false
